In [20]:
# Sesha Sai Sreevani Kappagantula
# Load libraries
from sklearn.ensemble import AdaBoostClassifier
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import log_loss
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn import tree
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import export_graphviz

#load the iris dataset
iris = load_iris()
X = pd.DataFrame(iris.data[:, :], columns = iris.feature_names[:])
y = pd.DataFrame(iris.target, columns =["Species"])

#split the dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

#train and predict using Decisiontree classifier for all 4 features with depth=1
lr = AdaBoostClassifier(base_estimator=tree.DecisionTreeClassifier(max_depth=1),n_estimators=50,
                         learning_rate=1,
                         random_state=0)
lr.fit(X_train, y_train)
y_pred=lr.predict(X_test)

#metrics valuation
print('results after training with decision tree of depth=1')
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print('Accuracy: %.2f' % accuracy_score(y_test, y_pred))

# Visualize the Tree
# Creates dot file named tree.dot
export_graphviz(
            lr.estimators_[0],
            out_file =  "Tree_" +"depth1"+".dot",
            feature_names = list(X.columns),
            class_names = iris.target_names,
            filled = True,
            rounded = True)

#train and predict using Decisiontree classifier for all 4 features with depth=2
lr = AdaBoostClassifier(base_estimator=tree.DecisionTreeClassifier(max_depth=2),n_estimators=50,
                         learning_rate=1,
                         random_state=0)
lr.fit(X_train, y_train)
y_pred=lr.predict(X_test)

#metrics valuation
print('\nresults after training with decision tree of depth=2')
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print('Accuracy: %.2f' % accuracy_score(y_test, y_pred))

# Visualize the Tree
# Creates dot file named tree.dot
export_graphviz(
            lr.estimators_[0],
            out_file =  "Tree_" +"depth2"+".dot",
            feature_names = list(X.columns),
            class_names = iris.target_names,
            filled = True,
            rounded = True)

#train and predict using Decisiontree classifier for all 4 features with depth=3
lr = AdaBoostClassifier(base_estimator=tree.DecisionTreeClassifier(max_depth=3),n_estimators=50,
                         learning_rate=1,
                         random_state=0)
lr.fit(X_train, y_train)
y_pred=lr.predict(X_test)

#metrics valuation
print('\nresults after training with decision tree of depth=3')
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print('Accuracy: %.2f' % accuracy_score(y_test, y_pred))

# Visualize the Tree
# Creates dot file named tree.dot
export_graphviz(
            lr.estimators_[0],
            out_file =  "Tree_" +"depth3"+".dot",
            feature_names = list(X.columns),
            class_names = iris.target_names,
            filled = True,
            rounded = True)

#train and predict using Decisiontree classifier for all 4 features with depth=4
lr = AdaBoostClassifier(base_estimator=tree.DecisionTreeClassifier(max_depth=4),n_estimators=50,
                         learning_rate=1,
                         random_state=0)
lr.fit(X_train, y_train)
y_pred=lr.predict(X_test)

#metrics valuation
print('\nresults after training with decision tree of depth=4')
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print('Accuracy: %.2f' % accuracy_score(y_test, y_pred))

# Visualize the Tree
# Creates dot file named tree.dot
export_graphviz(
            lr.estimators_[0],
            out_file =  "Tree_" +"depth4"+".dot",
            feature_names = list(X.columns),
            class_names = iris.target_names,
            filled = True,
            rounded = True)

#train and predict using Decisiontree classifier for all 4 features with depth=5
lr = AdaBoostClassifier(base_estimator=tree.DecisionTreeClassifier(max_depth=5),n_estimators=50,
                         learning_rate=1,
                         random_state=0)
lr.fit(X_train, y_train)
y_pred=lr.predict(X_test)

#metrics valuation
print('\nresults after training with decision tree of depth=5')
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print('Accuracy: %.2f' % accuracy_score(y_test, y_pred))

# Visualize the Tree
# Creates dot file named tree.dot
export_graphviz(
            lr.estimators_[0],
            out_file =  "Tree_" +"depth5"+".dot",
            feature_names = list(X.columns),
            class_names = iris.target_names,
            filled = True,
            rounded = True)

#train and predict using Decisiontree classifier for all 4 features with depth=6
lr = AdaBoostClassifier(base_estimator=tree.DecisionTreeClassifier(max_depth=6),n_estimators=50,
                         learning_rate=1,
                         random_state=0)
lr.fit(X_train, y_train)
y_pred=lr.predict(X_test)

#metrics valuation
print('\nresults after training with decision tree of depth=6')
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print('Accuracy: %.2f' % accuracy_score(y_test, y_pred))

# Visualize the Tree
# Creates dot file named tree.dot
export_graphviz(
            lr.estimators_[0],
            out_file =  "Tree_" +"depth6"+".dot",
            feature_names = list(X.columns),
            class_names = iris.target_names,
            filled = True,
            rounded = True)

print("6 dot files tree_depth.dot will be downloaded which contain the tree visualizations")

//anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
//anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
//anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
//anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example 

results after training with decision tree of depth=1
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       0.85      0.94      0.89        18
           2       0.89      0.73      0.80        11

    accuracy                           0.91        45
   macro avg       0.91      0.89      0.90        45
weighted avg       0.91      0.91      0.91        45

[[16  0  0]
 [ 0 17  1]
 [ 0  3  8]]
Accuracy: 0.91

results after training with decision tree of depth=2
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      0.67      0.80        18
           2       0.65      1.00      0.79        11

    accuracy                           0.87        45
   macro avg       0.88      0.89      0.86        45
weighted avg       0.91      0.87      0.87        45

[[16  0  0]
 [ 0 12  6]
 [ 0  0 11]]
Accuracy: 0.87

results after training wit

//anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
#Note: 6 dot files will be downloaded when the code is ran.
#These contain the tree visualizations for 6 the cases

In [ ]:
'''Results of previous assignment(using Decision tree classifier)

    Depths           Accuracy when gini      Accuracy when entropy

    Depth 1:               0.8666                 0.8666
    Depth 2:               0.8333                 0.8333
    Depth 3:               0.8666                 0.9
    Depth 4:               0.9333                 0.9
    Depth 5:               0.9333                 0.9333
    Depth 6:               0.9                    0.9333'''

In [ ]:
'''Results of this assignment (using AdaBoost classifier)

    Depths         Accuracy
    
    Depth1:        0.91
    Depth2:        0.87
    Depth3:        0.98
    Depth4:        0.98
    Depth5:        0.98
    Depth6:        0.98
'''

In [ ]:
'''Conclusion:
   --We observed that the accuracy at depth 1 itself AdaBoost classifier is giving accuracy higher than 
   Decision tree classifier used with depth1
   
   --We also observe that higher accuracy is obtained at lower depths very quickly by AdaBoost classifier than with
   Decision tree classifier.At depth 3 itself it attained 0.98 accuracy which is very high and good
   
   --Furthermore, we do not see any overfitting scenario as in Decision tree.The accuracy is seen to be stable after 
   depth 3 than decreasing 
   
   -However, on overall,AdaBoost clearly is giving higher accuracy than Decision tree in our assignment 
   even in its worst case 
   
'''